name: "Trainings: Singapore"

on:
  schedule:
    # Monday 09:40 UTC
    - cron: "40 9 * * 1"
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/trainings-scrape-reusable.yml
    with:
      country: Singapore
    secrets: inherit
