name: "Trainings: Netherlands"

on:
  schedule:
    # Monday 08:20 UTC
    - cron: "20 8 * * 1"
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/trainings-scrape-reusable.yml
    with:
      country: Netherlands
    secrets: inherit
