name: "Trainings: Germany"

on:
  schedule:
    # Monday 07:20 UTC
    - cron: "20 7 * * 1"
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/trainings-scrape-reusable.yml
    with:
      country: Germany
    secrets: inherit
