name: "Trainings: Czech Republic"

on:
  schedule:
    # Monday 08:00 UTC
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/trainings-scrape-reusable.yml
    with:
      country: Czech Republic
    secrets: inherit
